# Generated by Django 6.0.5 on 2026-05-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='folio',
            field=models.PositiveBigIntegerField(editable=False, unique=True),
        ),
    ]
