# Generated by Django 6.0.5 on 2026-05-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_report_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='folio',
            field=models.PositiveBigIntegerField(editable=False, unique=True),
        ),
    ]
