# Generated by Django 6.0.5 on 2026-06-19 02:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_report_report_type_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='El registro debe tener un solo modelo',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('report__isnull', False), ('tramite__isnull', True)), models.Q(('report__isnull', True), ('tramite__isnull', False)), _connector='OR'), name='review_debe_tener_un_solo_modelo'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('report__isnull', False), ('user__isnull', False)), fields=('user', 'report'), name='unique_user_report_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('tramite__isnull', False), ('user__isnull', False)), fields=('user', 'tramite'), name='unique_user_tramite_review'),
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
