# Generated by Django 6.0.5 on 2026-05-29 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tramite_folio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='service',
        ),
        migrations.AddField(
            model_name='document',
            name='tramite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.tramite'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
