# Generated by Django 6.0.5 on 2026-06-19 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_passwordresetcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePaymentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requires_payment', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='api.service')),
            ],
        ),
    ]
