# Generated by Django 6.0.5 on 2026-05-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
