FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential libpq-dev gcc --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /app

RUN adduser --disabled-password --gecos '' appuser && chown -R appuser /app

USER appuser

ENV DJANGO_SETTINGS_MODULE=h2o.settings

CMD ["gunicorn", "h2o.wsgi:application", "--bind", "0.0.0.0:8000"]
